#!/usr/bin/env python3
import getpass
import os
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent
ENV_FILE = ROOT / ".env"
GRAPH_VERSION = os.getenv("META_GRAPH_VERSION", "v26.0")
EXPECTED_PAGE_NAME = "D6x8 Gamer"

MANAGED_KEYS = {
    "META_PAGE_ID_GAMING",
    "META_PAGE_ACCESS_TOKEN_GAMING",
    "META_USER_ACCESS_TOKEN_GAMING",
}


def graph_get(path, token, fields=None):
    params = {"access_token": token}
    if fields:
        params["fields"] = fields
    response = requests.get(
        f"https://graph.facebook.com/{GRAPH_VERSION}/{path}",
        params=params,
        timeout=60,
    )
    try:
        data = response.json()
    except Exception:
        data = {"error": {"message": response.text[:500]}}
    if not response.ok or "error" in data:
        error = data.get("error", {}) if isinstance(data, dict) else {}
        message = error.get("message") or f"HTTP {response.status_code}"
        code = error.get("code")
        detail = f"Meta API error: {message}"
        if code is not None:
            detail += f" (code {code})"
        raise RuntimeError(detail)
    return data


def write_env(values):
    existing = ENV_FILE.read_text(encoding="utf-8").splitlines() if ENV_FILE.exists() else []
    kept = []
    for line in existing:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            kept.append(line)
            continue
        key = line.split("=", 1)[0].strip()
        if key not in MANAGED_KEYS:
            kept.append(line)
    if kept and kept[-1].strip():
        kept.append("")
    kept.append("# Gaming Meta connection - generated by meta_connect_gaming.py")
    for key, value in values.items():
        kept.append(f"{key}={value}")
    kept.append("")
    ENV_FILE.write_text("\n".join(kept), encoding="utf-8")
    try:
        ENV_FILE.chmod(0o600)
    except OSError:
        pass


def main():
    print("D6x8 Gamer Facebook connection")
    print("Your token is hidden while you paste it and will not be printed.")
    user_token = getpass.getpass("Paste fresh Meta User Access Token: ").strip()
    if not user_token:
        raise SystemExit("No token entered.")

    pages = graph_get("me/accounts", user_token, fields="id,name,access_token,tasks")
    matches = [p for p in pages.get("data", []) if str(p.get("name") or "").strip().lower() == EXPECTED_PAGE_NAME.lower()]
    if not matches:
        visible = ", ".join(str(p.get("name") or "?") for p in pages.get("data", [])) or "none"
        print(f"D6x8 Gamer was not found. Pages returned by Meta: {visible}")
        print("Generate a fresh User Token with pages_show_list, pages_read_engagement, and pages_manage_posts, then try again.")
        raise SystemExit(1)

    page = matches[0]
    page_id = str(page.get("id") or "").strip()
    page_token = str(page.get("access_token") or "").strip()
    if not page_id or not page_token:
        raise SystemExit("Meta found D6x8 Gamer but did not return a usable Page token.")

    check = graph_get(page_id, page_token, fields="id,name")
    if str(check.get("id") or "") != page_id:
        raise SystemExit("Gaming Page validation failed.")

    write_env({
        "META_PAGE_ID_GAMING": page_id,
        "META_PAGE_ACCESS_TOKEN_GAMING": page_token,
        "META_USER_ACCESS_TOKEN_GAMING": user_token,
    })

    print("\nGAMING FACEBOOK CONNECTION SUCCESS")
    print(f"Page: {check.get('name')} ({page_id})")
    print("Saved securely in local .env as the GAMING profile.")
    print("TV Mind and existing Facebook settings were not changed.")


if __name__ == "__main__":
    main()
