#!/usr/bin/env python3
import getpass
import os
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent
ENV_FILE = ROOT / ".env"
GRAPH_VERSION = os.getenv("META_GRAPH_VERSION", "v26.0")
PAGE_ID = "1213992321791402"
EXPECTED_PAGE_NAME = "TVMind USA"
EXPECTED_IG_ID = "17841406232043396"
EXPECTED_IG_USERNAME = "dhruv6x8"

MANAGED_KEYS = {
    "META_GRAPH_VERSION",
    "META_PAGE_ID",
    "META_PAGE_ACCESS_TOKEN",
    "META_IG_USER_ID",
    "META_IG_USERNAME",
}


def graph_get(path, token, fields=None):
    params = {"access_token": token}
    if fields:
        params["fields"] = fields
    response = requests.get(
        f"https://graph.facebook.com/{GRAPH_VERSION}/{path}",
        params=params,
        timeout=60,
    )
    try:
        data = response.json()
    except Exception:
        data = {"error": {"message": response.text[:500]}}
    if not response.ok or "error" in data:
        error = data.get("error", {})
        message = error.get("message") or f"HTTP {response.status_code}"
        code = error.get("code")
        subcode = error.get("error_subcode")
        details = f"Meta API error: {message}"
        if code is not None:
            details += f" (code {code}"
            if subcode is not None:
                details += f", subcode {subcode}"
            details += ")"
        raise RuntimeError(details)
    return data


def write_env(values):
    existing = []
    if ENV_FILE.exists():
        existing = ENV_FILE.read_text(encoding="utf-8").splitlines()

    kept = []
    for line in existing:
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in line:
            kept.append(line)
            continue
        key = line.split("=", 1)[0].strip()
        if key not in MANAGED_KEYS:
            kept.append(line)

    if kept and kept[-1].strip():
        kept.append("")
    kept.append("# Meta connection - generated by meta_connect.py")
    for key, value in values.items():
        kept.append(f"{key}={value}")
    kept.append("")

    ENV_FILE.write_text("\n".join(kept), encoding="utf-8")
    try:
        ENV_FILE.chmod(0o600)
    except OSError:
        pass


def main():
    print("Meta Reaction Factory connection test")
    print(f"Expected Page: {EXPECTED_PAGE_NAME} ({PAGE_ID})")
    print(f"Expected Instagram: @{EXPECTED_IG_USERNAME} ({EXPECTED_IG_ID})")
    print("Your token will be hidden while you paste it and will never be printed.")
    user_token = getpass.getpass("Paste fresh Meta User Access Token: ").strip()
    if not user_token:
        raise SystemExit("No token entered.")

    fields = "id,name,access_token,instagram_business_account{id,username}"
    try:
        page = graph_get(PAGE_ID, user_token, fields=fields)
    except RuntimeError as exc:
        print("\nCONNECTION FAILED")
        print(exc)
        print("Generate a fresh User Token in Graph API Explorer with:")
        print("pages_show_list, pages_read_engagement, pages_manage_posts, instagram_basic, instagram_content_publish")
        raise SystemExit(1)

    page_token = (page.get("access_token") or "").strip()
    ig = page.get("instagram_business_account") or {}
    ig_id = str(ig.get("id") or "")
    ig_username = str(ig.get("username") or "")

    if str(page.get("id")) != PAGE_ID:
        raise SystemExit("Meta returned an unexpected Page ID.")
    if not page_token:
        raise SystemExit("Page was found, but Meta did not return a Page access token.")

    if not ig_id:
        print("\nPAGE CONNECTED, INSTAGRAM NOT RETURNED")
        print(f"Page: {page.get('name')} ({page.get('id')})")
        print("The Facebook Page token works, but Meta did not return the linked Instagram account.")
        raise SystemExit(2)

    values = {
        "META_GRAPH_VERSION": GRAPH_VERSION,
        "META_PAGE_ID": PAGE_ID,
        "META_PAGE_ACCESS_TOKEN": page_token,
        "META_IG_USER_ID": ig_id,
        "META_IG_USERNAME": ig_username or EXPECTED_IG_USERNAME,
    }
    write_env(values)

    print("\nMETA CONNECTION SUCCESS")
    print(f"Facebook Page: {page.get('name')} ({page.get('id')})")
    print(f"Instagram: @{ig_username or '?'} ({ig_id})")
    if ig_id != EXPECTED_IG_ID:
        print("Warning: Instagram ID differs from the account previously seen in Business Suite.")
    print(f"Saved securely to: {ENV_FILE}")
    print("No access token was printed.")


if __name__ == "__main__":
    main()
